apiVersion: apps/v1
kind: Deployment
metadata:
  name: Application
  labels:
    app: Application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Application
  template:
    metadata:
      labels:
        app: Application
    spec:
      containers:
      - name: Application
        image: mnraomq/cicd-gitops:1
        ports:
        - containerPort: 8080
